### ISSUE TITLE
ImportError: cannot import name 'optim' from 'optim_cy' (unknown location)

### ISSUE THREAD

**Issue by AliYoussef96** [EDISS-intake2-team4/rots-py#3]
Hi,

I got this error every time I am trying to import rotspy, 
``ImportError: cannot import name 'optim' from 'optim_cy' (unknown location)``

I believe this is because the package trying to import ``optim_cy from optim``.
So deleting this line from two files ``rots.py`` and ``helpers.py`` and importing optim only solved the problem.

https://github.com/EDISS-intake2-team4/rots-py/blob/8bfc826eaa5ec58f745cd81a9a14aa030fd80da7/src/rotspy/helpers.py#L7

https://github.com/EDISS-intake2-team4/rots-py/blob/8bfc826eaa5ec58f745cd81a9a14aa030fd80da7/src/rotspy/rots.py#L10

**Comment by fariduca** [comment]
Fixed as of version 1.2.2
